<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation.Content\Automation.Content.csproj" />
    <ProjectReference Include="..\Automation.Domain\Automation.Domain.csproj" />
    <ProjectReference Include="..\Automation.Persistence\Automation.Persistence.csproj" />
    <ProjectReference Include="..\Automation.Simulation\Automation.Simulation.csproj" />
    <ProjectReference Include="..\Automation.Tools\Automation.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stride.Core.Assets.CompilerApp" IncludeAssets="build;buildTransitive" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" PrivateAssets="all" />
    <PackageReference Include="NuGet.Packaging" PrivateAssets="all" />
    <PackageReference Include="NuGet.Protocol" PrivateAssets="all" />
    <PackageReference Include="System.Security.Cryptography.Xml" PrivateAssets="all" />
    <PackageReference Include="Stride.Engine" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\imported\kenney-cursor-pack\*.png" />
    <EmbeddedResource Include="Assets\imported\kenney-furniture-kit\washer_SW.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Automation.Client.Stride.sdpkg" />
    <None Include="Assets\Imported\KenneyFurnitureKit\Washer.sdm3d" />
    <None Include="Resources\Imported\KenneyFurnitureKit\washer.glb" />
    <None Include="Resources\Audio\*.wav" />
  </ItemGroup>

</Project>
